### ISSUE TITLE
Regression: No flags shown

### ISSUE THREAD

**Issue by ProfJanetDavis** [gender-bias/gender-bias-web#47]
**Describe the bug**
I am no longer seeing any flags highlighted. 

**To Reproduce**
1. Run `genderbias-server` and `yarn serve`
2. Open the given URL in a browser
3. Paste in `examples/letterOfRecW`
4. See summaries but no flags.

**Expected behavior**
I expected to see some words flagged. None are.

**Additional context**
From using `git bisect`, I think something went wrong between commit 1c50aa48d39f7768a8411facbe5872974f92f56f and commit e5acf58, when getting data from the public API server instead of a local server.

**Estimate**
We estimate it will take two developers a full day (5 points) to figure out what went wrong and fix it. We should spend some time investigating on our own to figure out what questions @j6k4m8 can best help us answer.

**Comment by ProfJanetDavis** [comment]
@nidhi2509 identified 482699b as the last good commit. The next commit after that is af9014e

**Comment by ProfJanetDavis** [comment]
Hmm, both seem to be good as we are testing together.

**Comment by ProfJanetDavis** [comment]
We tried [`git bisect`](https://stackoverflow.com/questions/4713088/how-to-use-git-bisect), and learned that e5acf58aad1b252643099d7bc6712d0e3e63c0c0 really is the first bad commit.

This leads me back to the theory that something subtle changed in the API server with the move to the cloud, that the web interface code is not accounting for.

**Comment by j6k4m8** [comment]
there's also a trailing slash in the new URL that wasn't there previously. not likely the culprit, but worth confirming that this isn't breaking anything downstream

**Comment by ProfJanetDavis** [comment]
The following screenshot is for e5acf58 running against `api.biascorrect.org`. Note the absence of any flags under "Effort vs Accomplishment," which are the only ones we would see in the web interface.  

<img width="1365" alt="Screen Shot 2020-08-11 at 2 38 03 PM" src="https://user-images.githubusercontent.com/19829843/89951513-6ad93b00-dbe0-11ea-8db5-f775ccc46ed5.png">

**Comment by ProfJanetDavis** [comment]
Note there are flags for at least two other detectors, probably the ones for male and female words.

Could this be a problem with `spacy` on api.biascorrect.org? The "Effort vs Accomplishment" detector is the only one using the `spacy` module. Is it running? Is it installed? Hey @j6k4m8 ?

**Comment by j6k4m8** [comment]
Unfortunately, that's probably a limitation of our wordlist rather than a bug: I don't think there are any attributions of effort-like adjectives in this sample (from the part I can see in the screenshot above).

For example,

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/693511/89952145-b4368400-dbfa-11ea-848c-3e68a8ee7d6d.png">

Here, "willing" is an adjective attributable to "she".

spacy is definitely installed and working on the server, but we may need to focus some attention on new, smarter detectors.

**Comment by j6k4m8** [comment]
Incidentally, despite the above flag, the `willing` Blurb is not highlighted with a tooltip:

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/693511/89952290-f65fc580-dbfa-11ea-8101-55a3f59c1fe6.png">

**Comment by ProfJanetDavis** [comment]
@j6k4m8, our letter was the standard `example_letters/letterOfRecW`

**Comment by ProfJanetDavis** [comment]
Here's a screenshot with the current master.

<img width="1365" alt="Screen Shot 2020-08-11 at 2 54 58 PM" src="https://user-images.githubusercontent.com/19829843/89952781-b4c32080-dbe2-11ea-9d7f-1bb74ca8660e.png">

And then replacing "https://api.biascorrect.org" with "http://localhost:5000". Look at all those flags.

<img width="1365" alt="Screen Shot 2020-08-11 at 2 48 45 PM" src="https://user-images.githubusercontent.com/19829843/89952372-fd2e0e80-dbe1-11ea-98e2-1a05cdaf6299.png">

**Comment by ProfJanetDavis** [comment]
I'm going back and looking at your last screenshot, @j6k4m8 . I wonder if we all need to try debugging this together live, because we are clearly seeing different things.

**Comment by j6k4m8** [comment]
I think that may be not-latest-master on the gender-bias codebase running on your localhost:5000 (?)

Which is to say: "willingness" in the sample document is a noun[phrase] rather than an adjective, so while it used to be caught by the naïve wordlist checker, our new fancier spacy-based adjective-detection code misses it since it can't tell to whom the willingness is being attributed. (Yes, still a problem, but a different problem!)

**Comment by ProfJanetDavis** [comment]
You may be right about that.

**Comment by ProfJanetDavis** [comment]
This issue is superseded by #51 and [gender-bias#82](https://github.com/gender-bias/gender-bias/issues/82).
